import { Position, PositionChange, Meta } from './types';
import positionsData from '../../public/data/positions.json';
import changesData from '../../public/data/changes.json';
import metaData from '../../public/data/meta.json';
import profileFieldsData from '../../public/data/profile-fields.json';
import allProfilesData from '../../public/data/all-profiles.json';
import { getStateForDiocese } from './diocese-lookup';
import { extractCity } from './profile-helpers';

// Pre-computed enriched data (generated by scripts/enrich-positions.js)
// These files contain church_info and parochial data already attached.
let enrichedPositions: Record<string, unknown>[] | null = null;
let enrichedExtended: Record<string, unknown>[] | null = null;

try {
  enrichedPositions = require('../../public/data/enriched-positions.json');
} catch { /* Will fall back to raw positions */ }

try {
  enrichedExtended = require('../../public/data/enriched-extended.json');
} catch { /* Will fall back to profile-based extended */ }

const profileFields = profileFieldsData as unknown as Record<string, Array<{ label: string; value: string }>>;

interface RawProfile {
  vh_id: number;
  profile_url: string;
  diocese: string;
  congregation: string;
  position_type: string;
  status: string;
  all_fields: Array<{ label: string; value: string }>;
  [key: string]: unknown;
}

const allProfiles = allProfilesData as unknown as RawProfile[];

export function getPositions(): Position[] {
  // Use enriched data if available (pre-computed by build script)
  const rawPositions = (enrichedPositions || positionsData) as unknown as Record<string, unknown>[];

  const publicPositions = rawPositions.map(raw => {
    const pos = raw as unknown as Position;
    const vhId = pos.vh_id;
    return {
      ...pos,
      city: pos.city || extractCity(pos.name),
      visibility: 'public' as const,
      deep_scrape_fields: pos.deep_scrape_fields || (vhId ? profileFields[String(vhId)] : undefined),
    };
  });

  const publicVhIds = new Set(publicPositions.map(p => p.vh_id).filter(Boolean));

  // Extended positions from enriched data or raw profiles
  const extendedPositions: Position[] = [];

  if (enrichedExtended) {
    for (const ext of enrichedExtended) {
      const e = ext as Record<string, unknown>;
      const vhId = e.vh_id as number;
      if (publicVhIds.has(vhId)) continue;

      const diocese = (e.diocese as string) || '';
      const profile = allProfiles.find(p => p.vh_id === vhId);

      extendedPositions.push({
        id: `vh_${vhId}`,
        name: (e.name as string) || `Position in ${diocese}`,
        diocese,
        state: getStateForDiocese(diocese),
        organization_type: '',
        position_type: (e.position_type as string) || '',
        receiving_names_from: '',
        receiving_names_to: '',
        updated_on_hub: '',
        first_seen: '',
        last_seen: '',
        status: 'active',
        details_url: '',
        visibility: 'extended',
        vh_status: (e.vh_status as string) || '',
        vh_id: vhId,
        profile_url: (e.profile_url as string) || '',
        deep_scrape_fields: profile?.all_fields,
        church_info: e.church_info as Position['church_info'],
        parochial: e.parochial as Position['parochial'],
      });
    }
  } else {
    // Fallback: build extended positions from raw profiles (no enrichment)
    const activeStatuses = new Set(['Receiving names', 'Reopened']);
    for (const profile of allProfiles) {
      if (!activeStatuses.has(profile.status)) continue;
      if (publicVhIds.has(profile.vh_id)) continue;

      const hasName = !!profile.congregation;
      const hasSalary = !!profile.salary_range;
      const hasAttendance = !!profile.avg_sunday_attendance && profile.avg_sunday_attendance !== '0';
      if (!hasName && !hasSalary && !hasAttendance) continue;

      const diocese = profile.diocese || '';
      extendedPositions.push({
        id: `vh_${profile.vh_id}`,
        name: profile.congregation || `Position in ${diocese}`,
        diocese,
        state: getStateForDiocese(diocese),
        organization_type: '',
        position_type: profile.position_type || '',
        receiving_names_from: '',
        receiving_names_to: '',
        updated_on_hub: '',
        first_seen: '',
        last_seen: '',
        status: 'active',
        details_url: '',
        visibility: 'extended',
        vh_status: profile.status,
        vh_id: profile.vh_id,
        profile_url: profile.profile_url,
        deep_scrape_fields: profile.all_fields,
      });
    }
  }

  return [...publicPositions, ...extendedPositions];
}

export function getChanges(): PositionChange[] {
  return changesData as PositionChange[];
}

export function getMeta(): Meta {
  return metaData as Meta;
}

export function getUniqueValues(positions: Position[], field: keyof Position): string[] {
  const values = new Set<string>();
  for (const p of positions) {
    const val = p[field];
    if (typeof val === 'string' && val.trim()) {
      values.add(val.trim());
    }
  }
  return Array.from(values).sort();
}

export function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return '1 day ago';
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) {
    const weeks = Math.floor(diffDays / 7);
    return weeks === 1 ? '1 week ago' : `${weeks} weeks ago`;
  }
  const months = Math.floor(diffDays / 30);
  return months === 1 ? '1 month ago' : `${months} months ago`;
}
