import { Position, PositionChange, Meta } from './types';
import positionsData from '../../public/data/positions.json';
import changesData from '../../public/data/changes.json';
import metaData from '../../public/data/meta.json';
import profileFieldsData from '../../public/data/profile-fields.json';
import allProfilesData from '../../public/data/all-profiles.json';
import { getStateForDiocese } from './diocese-lookup';
import { extractCity } from './profile-helpers';

// Pre-computed enriched data (generated by scripts/enrich-positions.js)
let enrichedPositions: Record<string, unknown>[] | null = null;
let enrichedExtended: Record<string, unknown>[] | null = null;

try {
  enrichedPositions = require('../../public/data/enriched-positions.json');
} catch { /* Will fall back to raw positions */ }

try {
  enrichedExtended = require('../../public/data/enriched-extended.json');
} catch { /* Will fall back to profile-based extended */ }

const profileFields = profileFieldsData as unknown as Record<string, Array<{ label: string; value: string }>>;

interface RawProfile {
  vh_id: number;
  profile_url: string;
  diocese: string;
  congregation: string;
  position_type: string;
  status: string;
  all_fields: Array<{ label: string; value: string }>;
  [key: string]: unknown;
}

const allProfiles = allProfilesData as unknown as RawProfile[];

// Parse MM/DD/YYYY or ISO date string into Date
function parseDate(dateStr: string): Date | null {
  if (!dateStr) return null;
  // Try MM/DD/YYYY
  const mdyMatch = dateStr.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (mdyMatch) {
    return new Date(parseInt(mdyMatch[3]), parseInt(mdyMatch[1]) - 1, parseInt(mdyMatch[2]));
  }
  // Try ISO
  const d = new Date(dateStr);
  return isNaN(d.getTime()) ? null : d;
}

// Determine if a position is "new" based on receiving dates or update date
function computeIsNew(pos: { receiving_names_from?: string; updated_on_hub?: string }): boolean {
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  // Primary: receiving_names_from date within last 30 days
  const receivingDate = parseDate(pos.receiving_names_from || '');
  if (receivingDate && receivingDate >= thirtyDaysAgo) return true;

  // Fallback: updated_on_hub within last 14 days
  const updatedDate = parseDate(pos.updated_on_hub || '');
  if (updatedDate) {
    const fourteenDaysAgo = new Date();
    fourteenDaysAgo.setDate(fourteenDaysAgo.getDate() - 14);
    if (updatedDate >= fourteenDaysAgo) return true;
  }

  return false;
}

export function getPositions(): Position[] {
  // Use enriched data if available (pre-computed by build script)
  const rawPositions = (enrichedPositions || positionsData) as unknown as Record<string, unknown>[];

  const publicPositions = rawPositions.map(raw => {
    const pos = raw as unknown as Position;
    // Extract vh_id from profile_url if missing
    let vhId = pos.vh_id;
    if (!vhId && pos.profile_url) {
      const m = pos.profile_url.match(/PositionView\/(\d+)/);
      if (m) vhId = parseInt(m[1], 10);
    }
    // Look up VH status from profile if not on position
    const profile = vhId ? allProfiles.find(p => p.vh_id === vhId) : undefined;

    // Derive vh_status: use enriched value, then profile lookup, then map scraper status
    let vhStatus = pos.vh_status || profile?.status || '';
    if (!vhStatus && pos.status === 'new') {
      // Scraper status "new" means it appeared in VH search results recently
      vhStatus = 'Receiving names';
    }

    return {
      ...pos,
      vh_id: vhId ?? pos.vh_id,
      city: pos.city || extractCity(pos.name),
      state: pos.state || (pos.church_info as Position['church_info'])?.state || getStateForDiocese(pos.diocese || ''),
      visibility: 'public' as const,
      vh_status: vhStatus,
      deep_scrape_fields: pos.deep_scrape_fields || (vhId ? profileFields[String(vhId)] : undefined),
      is_new: computeIsNew(pos),
    };
  });

  const publicVhIds = new Set(publicPositions.map(p => p.vh_id).filter(Boolean));

  // Extended positions: ALL profiles not in search results
  const extendedPositions: Position[] = [];

  if (enrichedExtended) {
    for (const ext of enrichedExtended) {
      const e = ext as Record<string, unknown>;
      const vhId = e.vh_id as number;
      if (publicVhIds.has(vhId)) continue;

      const diocese = (e.diocese as string) || '';
      const profile = allProfiles.find(p => p.vh_id === vhId);
      const state = (e.state as string) || (e.church_info as Position['church_info'])?.state || getStateForDiocese(diocese);

      const receivingFrom = (e.receiving_names_from as string) || '';
      const receivingTo = (e.receiving_names_to as string) || '';
      const vhStatus = (e.vh_status as string) || '';

      extendedPositions.push({
        id: `vh_${vhId}`,
        name: (e.name as string) || `Position in ${diocese}`,
        diocese,
        state,
        organization_type: '',
        position_type: (e.position_type as string) || '',
        receiving_names_from: receivingFrom,
        receiving_names_to: receivingTo,
        updated_on_hub: '',
        first_seen: '',
        last_seen: '',
        status: vhStatus || 'active',
        details_url: '',
        visibility: 'extended',
        vh_status: vhStatus,
        vh_id: vhId,
        profile_url: (e.profile_url as string) || '',
        deep_scrape_fields: profile?.all_fields,
        church_info: e.church_info as Position['church_info'],
        match_confidence: (e.match_confidence as Position['match_confidence']) || undefined,
        parochial: e.parochial as Position['parochial'],
        diocese_percentiles: e.diocese_percentiles as Position['diocese_percentiles'],
        estimated_total_comp: e.estimated_total_comp as number | undefined,
        comp_breakdown: e.comp_breakdown as Position['comp_breakdown'],
        is_new: computeIsNew({ receiving_names_from: receivingFrom }),
      });
    }
  }

  return [...publicPositions, ...extendedPositions];
}

export function getChanges(): PositionChange[] {
  return changesData as PositionChange[];
}

export function getMeta(): Meta {
  return metaData as Meta;
}

export function getUniqueValues(positions: Position[], field: keyof Position): string[] {
  const values = new Set<string>();
  for (const p of positions) {
    const val = p[field];
    if (typeof val === 'string' && val.trim()) {
      values.add(val.trim());
    }
  }
  return Array.from(values).sort();
}

export function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return '1 day ago';
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) {
    const weeks = Math.floor(diffDays / 7);
    return weeks === 1 ? '1 week ago' : `${weeks} weeks ago`;
  }
  const months = Math.floor(diffDays / 30);
  return months === 1 ? '1 month ago' : `${months} months ago`;
}
